name: control_shell
description: "A new Flutter project."
version: 0.0.2+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  #   path: ^1.8.0

  # https://pub.dev/packages/process_run
  process_run: 0.13.2

  # https://pub.dev/packages/source_gen
  source_gen: 1.4.0

  # https://pub.dev/packages/build
  build: 2.4.1

  # https://pub.dev/packages/code_builder
  code_builder: 4.7.0

  googleapis: ^13.2.0
  googleapis_auth: ^1.2.0

  yaml_writer: ^2.0.1
  xml: ^6.5.0
  archive: ^4.0.2
